### ISSUE TITLE
Cross Project Support

### ISSUE THREAD

**Issue by satrox28** [BESTSELLER/backstage-plugin-gkeusage-backend#32]
Hi,

We have the GKE dataset in a Project A and when the plugin tries to execute the BQ, would like to perform it from Project B. 

The backend plugin, currently throws below error.

```
User does not have bigquery.jobs.create permission in project A.
```

Related to Issue https://github.com/googleapis/nodejs-bigquery/issues/1030

**Comment by satrox28** [comment]
Hi @wrighbr created a PR https://github.com/BESTSELLER/backstage-plugin-gkeusage-backend/pull/36 for this issue, please take a look.

**Comment by wrighbr** [comment]
Released
